DROP DATABASE IF EXISTS DINOSAURIO;
CREATE DATABASE DINOSAURIO;
USE DINOSAURIO;
DROP TABLE IF EXISTS USUARIOS;
CREATE TABLE USUARIOS
	(id INT AUTO_INCREMENT PRIMARY KEY,
	nom_usuario VARCHAR(20),
	puntuacion INT);
DROP TABLE IF EXISTS RANKING;
CREATE TABLE RANKING
	(id INT AUTO_INCREMENT,
	puntuacion INT,
	CONSTRAINT PK_RANKING PRIMARY KEY (id),
	CONSTRAINT FK_ID FOREIGN KEY (id) REFERENCES USUARIOS(id) ON UPDATE CASCADE);
	
	


DROP DATABASE IF EXISTS DINOSAURIO;
CREATE DATABASE DINOSAURIO;
USE DINOSAURIO;
DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS RANKING;
CREATE TABLE USUARIOS
	(id INT AUTO_INCREMENT,
	nom_usuario VARCHAR (20),
	CONSTRAINT PK_ID PRIMARY KEY (id));
CREATE TABLE RANKING
	(id INT,
	nom_usuario VARCHAR (30),
	puntuacion INT,
	CONSTRAINT PK_LINEAS_FACTURA PRIMARY KEY (id,nom_usuario),
	CONSTRAINT FK_LINEAS_FACTURAS FOREIGN KEY (id) REFERENCES USUARIOS(id) ON UPDATE CASCADE,
	CONSTRAINT FK_LINEAS_ARTICULOS FOREIGN KEY (nom_usuario) REFERENCES USUARIOS(nom_usuario) ON UPDATE CASCADE);